// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ZLt6dSwNojAyzXEPjq8JBUmnNrVA74A',
    appId: '1:765954495105:web:158bd808694d678b197380',
    messagingSenderId: '765954495105',
    projectId: 'scholr-c057b',
    authDomain: 'scholr-c057b.firebaseapp.com',
    storageBucket: 'scholr-c057b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrcJXOCTZunV0Dch2pyJJszYAaooNFSpw',
    appId: '1:765954495105:android:d0aa209f541eab33197380',
    messagingSenderId: '765954495105',
    projectId: 'scholr-c057b',
    storageBucket: 'scholr-c057b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkURndpdvPZ9IlBZTrQ7o4-Y_rTeKh78U',
    appId: '1:765954495105:ios:e194d5a4f69f2bb9197380',
    messagingSenderId: '765954495105',
    projectId: 'scholr-c057b',
    storageBucket: 'scholr-c057b.firebasestorage.app',
    iosBundleId: 'com.example.edubridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkURndpdvPZ9IlBZTrQ7o4-Y_rTeKh78U',
    appId: '1:765954495105:ios:e194d5a4f69f2bb9197380',
    messagingSenderId: '765954495105',
    projectId: 'scholr-c057b',
    storageBucket: 'scholr-c057b.firebasestorage.app',
    iosBundleId: 'com.example.edubridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-ZLt6dSwNojAyzXEPjq8JBUmnNrVA74A',
    appId: '1:765954495105:web:471fdd72f923b5e1197380',
    messagingSenderId: '765954495105',
    projectId: 'scholr-c057b',
    authDomain: 'scholr-c057b.firebaseapp.com',
    storageBucket: 'scholr-c057b.firebasestorage.app',
  );
}
